name: expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Let the solver find the best compatible versions
  # Pinned versions for stability
  provider: ^6.1.5
  intl: ^0.19.0
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  currency_picker: ^2.0.21
  share_plus: ^10.0.0
  pdf: ^3.11.1
  printing: ^5.14.2
  open_file: ^3.5.10
  permission_handler: ^12.0.1
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_launcher_icons: any

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/favicon_Complete.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/fonts/
    - .env

